apiVersion: v1
kind: Service
metadata:
  name:  helloapp-rtp-service
  namespace: helloapp
spec:
  type: NodePort
  selector:
    app: helloapp-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000